### PR TITLE
reader: always draw last progress update on EOF

### PR DESCRIPTION
**Pull request by vcaputo**

### CODE REVIEW

**Comment by tucksaun** [comment]
:+1:

**Comment by romainneutron** [comment]
\o/

**Comment by vcaputo** [comment]
Note this PR only fixes the 100% update for progress bars which have been updated at least once.

Since the code specifically called out not drawing the last update if no draws occurred (https://github.com/mitchellh/ioprogress/blob/master/reader.go#L83) I left that to be discussed here.

@mitchellh ping

**Comment by kelseyhightower** [comment]
@mitchellh First thanks for making this library public and we are pretty happy with it in rkt. I've noticed this issue a couple of times using rkt and this patch seems to resolve things for me.

Is there anything we can do to help move this along? Thanks.

**Comment by mitchellh** [comment]
@kelseyhightower has come from across the world to Berlin to meet me to tell me to merge this. And so it is so.

**Pull request merged**
